---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jenkins
        version: 0.2.0
    spec:
      containers:
      - name: jenkins
        image: jenkins:latest
        resources:
          requests:
            cpu: 0.5
            memory: 500Mi
          limits:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 8080
